# Generated by Django 3.0.2 on 2022-06-24 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='address_name',
            field=models.CharField(max_length=100),
        ),
    ]
